import type { CandidateValue } from "./types";

export const cookingMethodAndToolCandidates = [
  {
    value: "電子レンジ",
    aliases: ["レンジ", "でんしれんじ"],
    romaji: ["renji", "microwave"],
  },
  { value: "オーブンレンジ", aliases: ["レンジオーブン"], romaji: ["oven range"] },
  { value: "スチームオーブンレンジ", aliases: ["スチームオーブン"], romaji: ["steam oven"] },
  { value: "フライパン", romaji: ["furaipan"] },
  { value: "鍋", aliases: ["なべ"], romaji: ["nabe"] },
  { value: "片手鍋", aliases: ["かたてなべ"], romaji: ["katatenabe"] },
  { value: "両手鍋", aliases: ["りょうてなべ"], romaji: ["ryotenabe"] },
  { value: "深型フライパン", aliases: ["深型パン"], romaji: ["fukagata furaipan"] },
  { value: "卵焼き器", aliases: ["玉子焼き器", "卵焼きフライパン"], romaji: ["tamagoyakiki"] },
  { value: "土鍋", aliases: ["どなべ"], romaji: ["donabe"] },
  { value: "中華鍋", aliases: ["ちゅうかなべ", "ウォック"], romaji: ["chukanabe", "wok"] },
  { value: "スキレット", romaji: ["sukiretto", "skillet"] },
  { value: "グリルパン", romaji: ["grill pan"] },
  { value: "蒸し器", aliases: ["せいろ", "蒸籠"], romaji: ["mushiki", "seiro"] },
  { value: "圧力鍋", aliases: ["あつりょくなべ"], romaji: ["atsuryokunabe"] },
  { value: "電気圧力鍋", aliases: ["電気式圧力鍋"], romaji: ["denki atsuryokunabe"] },
  { value: "自動調理鍋", aliases: ["自動調理器"], romaji: ["jido chori nabe"] },
  { value: "無水鍋", aliases: ["むすいなべ"], romaji: ["musuinabe"] },
  { value: "低温調理器", aliases: ["低温調理機"], romaji: ["teion choriki", "sous vide"] },
  { value: "スロークッカー", aliases: ["電気煮込み鍋"], romaji: ["slow cooker"] },
  {
    value: "炊飯器",
    aliases: ["すいはんき", "炊飯ジャー"],
    romaji: ["suihanki", "rice cooker"],
  },
  { value: "ホームベーカリー", aliases: ["パン焼き機"], romaji: ["home bakery", "bread maker"] },
  { value: "ホットプレート", romaji: ["hotplate"] },
  { value: "たこ焼き器", aliases: ["たこ焼きプレート"], romaji: ["takoyakiki"] },
  { value: "ワッフルメーカー", aliases: ["ワッフル焼き器"], romaji: ["waffle maker"] },
  { value: "トースター", aliases: ["オーブントースター"], romaji: ["toaster"] },
  { value: "オーブン", romaji: ["oven"] },
  { value: "魚焼きグリル", aliases: ["グリル"], romaji: ["sakana yaki grill", "grill"] },
  {
    value: "ノンフライヤー",
    aliases: ["エアフライヤー", "エアーフライヤー"],
    romaji: ["non fryer", "air fryer"],
  },
  { value: "スープジャー", aliases: ["保温ジャー"], romaji: ["soup jar"] },
  { value: "保温調理鍋", romaji: ["hoon chori nabe"] },
  { value: "ミキサー", romaji: ["mixer"] },
  { value: "ブレンダー", romaji: ["blender"] },
  { value: "ハンドブレンダー", aliases: ["ブレンダー棒"], romaji: ["hand blender"] },
  { value: "フードプロセッサー", aliases: ["フープロ"], romaji: ["food processor"] },
  { value: "チョッパー", aliases: ["みじん切り器"], romaji: ["chopper"] },
  { value: "ジューサー", romaji: ["juicer"] },
  { value: "ミル", aliases: ["粉砕ミル"], romaji: ["mill"] },
  { value: "キッチンバサミ", aliases: ["キッチンはさみ"], romaji: ["kitchen basami"] },
  { value: "ピーラー", aliases: ["皮むき器"], romaji: ["peeler"] },
  { value: "スライサー", romaji: ["slicer"] },
  { value: "おろし器", aliases: ["おろし金"], romaji: ["oroshiki"] },
  { value: "ザル", aliases: ["ざる"], romaji: ["zaru"] },
  { value: "ボウル", aliases: ["ボール"], romaji: ["bowl"] },
  { value: "耐熱ボウル", aliases: ["レンジ対応ボウル"], romaji: ["tainetsu bowl"] },
  { value: "シリコンスチーマー", aliases: ["シリコン蒸し器"], romaji: ["silicone steamer"] },
  { value: "クッキングシート", aliases: ["オーブンシート"], romaji: ["cooking sheet"] },
  { value: "アルミホイル", aliases: ["ホイル"], romaji: ["aluminum foil"] },
  { value: "ラップ", aliases: ["食品ラップ"], romaji: ["wrap"] },

  {
    value: "ヘルシオ ホットクック",
    aliases: ["ホットクック", "Hot Cook"],
    romaji: ["healsio hotcook", "hotcook"],
  },
  { value: "ビストロ", aliases: ["Bistro", "パナソニック ビストロ"], romaji: ["bistro"] },
  {
    value: "クックフォーミー",
    aliases: ["Cook4me", "ティファール クックフォーミー"],
    romaji: ["cook4me", "cook for me"],
  },
  {
    value: "バルミューダ ザ・トースター",
    aliases: ["BALMUDA The Toaster", "バルミューダ トースター"],
    romaji: ["balmuda the toaster"],
  },
  {
    value: "アラジン グラファイトトースター",
    aliases: ["アラジン トースター", "グラファイトトースター"],
    romaji: ["aladdin graphite toaster"],
  },
  {
    value: "BRUNO コンパクトホットプレート",
    aliases: ["ブルーノ コンパクトホットプレート", "BRUNO ホットプレート"],
    romaji: ["bruno compact hot plate"],
  },
  { value: "BONIQ", aliases: ["ボニーク", "BONIQ 低温調理器"], romaji: ["boniq"] },

  { value: "火を使わない", aliases: ["非加熱"], romaji: ["hiwotsukawanai"] },
  { value: "和えるだけ", aliases: ["あえるだけ"], romaji: ["aerudake"] },
  { value: "焼く", aliases: ["焼き"], romaji: ["yaku"] },
  { value: "炒める", aliases: ["炒め"], romaji: ["itameru"] },
  { value: "煮る", aliases: ["煮込み"], romaji: ["niru"] },
  { value: "蒸す", aliases: ["蒸し"], romaji: ["musu"] },
  { value: "揚げる", aliases: ["揚げ"], romaji: ["ageru"] },
  { value: "揚げない", aliases: ["ノンフライ"], romaji: ["agenai"] },
  { value: "茹でる", aliases: ["ゆでる"], romaji: ["yuderu"] },
  { value: "炊く", aliases: ["炊き"], romaji: ["taku"] },
  { value: "漬ける", aliases: ["漬け"], romaji: ["tsukeru"] },
  { value: "冷やす", aliases: ["冷製"], romaji: ["hiyasu"] },
  { value: "温めるだけ", aliases: ["あたためるだけ"], romaji: ["atatamerudake"] },
  { value: "混ぜるだけ", aliases: ["まぜるだけ"], romaji: ["mazerudake"] },
  { value: "切るだけ", aliases: ["きるだけ"], romaji: ["kirudake"] },
] as const satisfies readonly CandidateValue[];
