import type { CandidateValue } from "./types";

export const dishTypeCandidates = [
  { value: "主菜", aliases: ["メイン", "主なおかず"], romaji: ["shusai", "main"] },
  { value: "副菜", aliases: ["サブおかず", "小さいおかず"], romaji: ["fukusai"] },
  { value: "汁物", aliases: ["汁もの", "スープ"], romaji: ["shirumono", "soup"] },
  { value: "主食", aliases: ["ごはん", "ご飯"], romaji: ["shushoku"] },
  { value: "ご飯もの", aliases: ["ごはんもの"], romaji: ["gohanmono"] },
  { value: "丼もの", aliases: ["丼", "どんぶり"], romaji: ["donburi"] },
  { value: "麺類", aliases: ["めん類", "麺"], romaji: ["menrui"] },
  { value: "サラダ", romaji: ["salad"] },
  { value: "小鉢", aliases: ["こばち"], romaji: ["kobachi"] },
  { value: "付け合わせ", aliases: ["つけあわせ"], romaji: ["tsukeawase"] },
  { value: "作り置き", aliases: ["つくりおき"], romaji: ["tsukurioki"] },
  { value: "おかず", aliases: ["おかず"], romaji: ["okazu"] },
  { value: "お弁当", aliases: ["弁当", "おべんとう"], romaji: ["obento"] },
  { value: "おつまみ", aliases: ["つまみ"], romaji: ["otsumami"] },
  { value: "常備菜", aliases: ["じょうびさい"], romaji: ["jobisai"] },
  { value: "ご飯のお供", aliases: ["ごはんのおとも"], romaji: ["gohan no otomo"] },
  { value: "保存食", aliases: ["ほぞんしょく"], romaji: ["hozonshoku"] },
  { value: "離乳食", aliases: ["りにゅうしょく"], romaji: ["rinyushoku"] },
  { value: "幼児食", aliases: ["ようじしょく"], romaji: ["yojishoku"] },
  { value: "鍋もの", aliases: ["鍋", "なべ"], romaji: ["nabemono"] },
  { value: "煮物", aliases: ["にもの"], romaji: ["nimono"] },
  { value: "炒め物", aliases: ["いためもの"], romaji: ["itamemono"] },
  { value: "焼き物", aliases: ["やきもの"], romaji: ["yakimono"] },
  { value: "揚げ物", aliases: ["あげもの"], romaji: ["agemono"] },
  { value: "蒸し物", aliases: ["むしもの"], romaji: ["mushimono"] },
  { value: "和え物", aliases: ["あえもの"], romaji: ["aemono"] },
  { value: "酢の物", aliases: ["すのもの"], romaji: ["sunomono"] },
  { value: "漬物", aliases: ["つけもの"], romaji: ["tsukemono"] },
  { value: "ソース・たれ", aliases: ["たれ", "タレ"], romaji: ["sauce", "tare"] },
  { value: "パン・粉もの", aliases: ["粉もの", "パン"], romaji: ["konamono"] },
  { value: "おやつ", romaji: ["oyatsu"] },
  { value: "デザート", aliases: ["スイーツ"], romaji: ["dessert", "sweets"] },
] as const satisfies readonly CandidateValue[];
