import type { CandidateValue } from "./types";

export const easeCandidates = [
  { value: "時短", aliases: ["短時間", "すぐできる"], romaji: ["jitan"] },
  { value: "手順少なめ", aliases: ["工程少なめ"], romaji: ["tejun sukuname"] },
  { value: "洗い物少なめ", aliases: ["洗いもの少なめ"], romaji: ["araimono sukuname"] },
  { value: "ワンパン", aliases: ["フライパンひとつ"], romaji: ["onepan"] },
  { value: "包丁少なめ", aliases: ["包丁をあまり使わない"], romaji: ["hocho sukuname"] },
  {
    value: "まな板・包丁なし",
    aliases: ["まな板なし", "包丁なし"],
    romaji: ["manaita hocho nashi"],
  },
  { value: "下ごしらえ少なめ", aliases: ["下準備少なめ"], romaji: ["shitago sukuname"] },
  { value: "火を使わない", aliases: ["非加熱"], romaji: ["hiwotsukawanai"] },
  { value: "ほったらかし", aliases: ["放置調理"], romaji: ["hottarakashi"] },
  { value: "混ぜるだけ", aliases: ["まぜるだけ"], romaji: ["mazerudake"] },
  { value: "和えるだけ", aliases: ["あえるだけ"], romaji: ["aerudake"] },
  { value: "温めるだけ", aliases: ["あたためるだけ"], romaji: ["atatamerudake"] },
  { value: "初心者向け", aliases: ["初心者でも作れる"], romaji: ["shoshinsha"] },
  { value: "失敗しにくい", aliases: ["失敗しづらい"], romaji: ["shippai shinikui"] },
  { value: "味つけ簡単", aliases: ["味付け簡単"], romaji: ["ajitsuke kantan"] },
  { value: "計量少なめ", aliases: ["計量が少ない"], romaji: ["keiryo sukuname"] },
  { value: "少ない材料で作れる", aliases: ["材料少なめ"], romaji: ["zairyo sukuname"] },
  {
    value: "家にある調味料で作れる",
    aliases: ["基本調味料で作れる"],
    romaji: ["ie ni aru chomiryo"],
  },
  { value: "片付け簡単", aliases: ["後片付け簡単"], romaji: ["katazuke kantan"] },
  { value: "節約", aliases: ["安く作れる"], romaji: ["setsuyaku"] },
  { value: "ボリューム重視", aliases: ["満足感重視"], romaji: ["volume"] },
  { value: "かさ増し", aliases: ["かさまし"], romaji: ["kasamashi"] },
  { value: "作り置き向き", aliases: ["作り置きしやすい"], romaji: ["tsukurioki muki"] },
  { value: "冷凍保存可", aliases: ["冷凍できる"], romaji: ["reito hozon"] },
  { value: "冷蔵保存可", aliases: ["冷蔵できる"], romaji: ["reizo hozon"] },
  { value: "お弁当に入れやすい", aliases: ["弁当向き"], romaji: ["bento muki"] },
  { value: "子どもと作れる", aliases: ["子供と作れる"], romaji: ["kodomo to tsukureru"] },
  { value: "取り分けしやすい", aliases: ["取り分け"], romaji: ["toriwake"] },
  { value: "大皿で出せる", aliases: ["大皿料理"], romaji: ["oozara"] },
] as const satisfies readonly CandidateValue[];
