import type { CandidateValue } from "./types";

export const foodMaterialCandidates = [
  { value: "米", aliases: ["こめ"], romaji: ["kome"] },
  { value: "ご飯", aliases: ["ごはん", "御飯"], romaji: ["gohan"] },
  { value: "玄米", aliases: ["げんまい"], romaji: ["genmai"] },
  { value: "雑穀米", aliases: ["ざっこくまい"], romaji: ["zakkokumai"] },
  { value: "もち", aliases: ["餅"], romaji: ["mochi"] },
  { value: "食パン", aliases: ["しょくぱん"], romaji: ["shokupan"] },
  { value: "フランスパン", romaji: ["furansupan"] },
  { value: "ロールパン", romaji: ["rorupan"] },
  { value: "うどん", romaji: ["udon"] },
  { value: "そば", aliases: ["蕎麦"], romaji: ["soba"] },
  { value: "そうめん", aliases: ["素麺"], romaji: ["somen"] },
  { value: "ひやむぎ", aliases: ["冷麦"], romaji: ["hiyamugi"] },
  { value: "パスタ", romaji: ["pasta"] },
  { value: "マカロニ", romaji: ["macaroni"] },
  { value: "中華麺", aliases: ["ちゅうかめん"], romaji: ["chukamen"] },
  { value: "焼きそば麺", aliases: ["やきそばめん"], romaji: ["yakisobamen"] },
  { value: "春雨", aliases: ["はるさめ"], romaji: ["harusame"] },
  { value: "ビーフン", romaji: ["bifun"] },
  { value: "オートミール", romaji: ["oatmeal"] },
  { value: "餃子の皮", aliases: ["ぎょうざの皮", "ギョウザの皮"], romaji: ["gyozanokawa"] },
  { value: "春巻きの皮", aliases: ["はるまきの皮"], romaji: ["harumakinokawa"] },
  { value: "ホットケーキミックス", romaji: ["hottokekimikkusu"] },
  { value: "小麦粉", aliases: ["こむぎこ"], romaji: ["komugiko"] },
  { value: "片栗粉", aliases: ["かたくりこ"], romaji: ["katakuriko"] },
  { value: "パン粉", aliases: ["ぱんこ"], romaji: ["panko"] },

  { value: "卵", aliases: ["たまご", "玉子", "タマゴ"], romaji: ["tamago"] },
  { value: "うずら卵", aliases: ["うずらたまご", "うずらの卵"], romaji: ["uzuratamago"] },
  { value: "豆腐", aliases: ["とうふ"], romaji: ["tofu"] },
  { value: "絹ごし豆腐", aliases: ["絹豆腐", "きぬごしどうふ"], romaji: ["kinugoshidofu"] },
  { value: "木綿豆腐", aliases: ["もめんどうふ"], romaji: ["momendofu"] },
  { value: "厚揚げ", aliases: ["あつあげ"], romaji: ["atsuage"] },
  { value: "油揚げ", aliases: ["あぶらあげ"], romaji: ["aburaage"] },
  { value: "納豆", aliases: ["なっとう"], romaji: ["natto"] },
  { value: "おから", romaji: ["okara"] },
  { value: "高野豆腐", aliases: ["こうやどうふ", "高野とうふ", "こうや"], romaji: ["koyadofu"] },
  { value: "豆乳", aliases: ["とうにゅう"], romaji: ["tonyu"] },
  { value: "ゆば", aliases: ["湯葉"], romaji: ["yuba"] },
  { value: "大豆", aliases: ["だいず"], romaji: ["daizu"] },
  { value: "ミックスビーンズ", romaji: ["mikkusubinz"] },
  { value: "枝豆", aliases: ["えだまめ"], romaji: ["edamame"] },

  { value: "鶏もも肉", aliases: ["とりもも肉", "鳥もも肉"], romaji: ["torimomoniku"] },
  { value: "鶏むね肉", aliases: ["鶏胸肉", "とりむね肉"], romaji: ["torimuneniku"] },
  { value: "鶏ささみ", aliases: ["ささみ"], romaji: ["sasami"] },
  { value: "鶏ひき肉", aliases: ["鶏挽肉", "とりひき肉"], romaji: ["torihikiniku"] },
  { value: "鶏手羽元", aliases: ["手羽元"], romaji: ["tebamoto"] },
  { value: "鶏手羽中", aliases: ["手羽中"], romaji: ["tebanaka"] },
  { value: "鶏手羽先", aliases: ["手羽先"], romaji: ["tebasaki"] },
  { value: "砂肝", aliases: ["すなぎも"], romaji: ["sunagimo"] },
  { value: "レバー", romaji: ["reba"] },

  { value: "豚こま肉", aliases: ["豚こま", "ぶたこま"], romaji: ["butakoma"] },
  { value: "豚バラ肉", aliases: ["豚ばら肉", "ぶたばら"], romaji: ["butabara"] },
  { value: "豚ひき肉", aliases: ["豚挽肉", "ぶたひき肉"], romaji: ["butahikiniku"] },
  { value: "豚ロース", romaji: ["butarosu"] },
  { value: "豚肩ロース", aliases: ["肩ロース"], romaji: ["katardosu", "butakatarosu"] },
  { value: "豚薄切り肉", aliases: ["豚薄切り"], romaji: ["butausugiri"] },
  { value: "豚しゃぶ肉", aliases: ["豚しゃぶ"], romaji: ["butashabu"] },
  { value: "豚もも肉", romaji: ["butamomoniku"] },
  { value: "スペアリブ", romaji: ["supearibu"] },

  { value: "牛こま肉", aliases: ["牛こま"], romaji: ["gyukoma"] },
  { value: "牛ひき肉", aliases: ["牛挽肉"], romaji: ["gyuhikiniku"] },
  { value: "牛薄切り肉", aliases: ["牛薄切り"], romaji: ["gyuusugiri"] },
  { value: "牛切り落とし肉", aliases: ["牛切り落とし"], romaji: ["gyukiriotoshi"] },
  { value: "牛ステーキ肉", aliases: ["ステーキ肉"], romaji: ["suteki"] },
  { value: "合いびき肉", aliases: ["合挽き肉", "合い挽き肉"], romaji: ["aibikiniku"] },
  { value: "ラム肉", aliases: ["羊肉"], romaji: ["ramuniku"] },
  { value: "鴨肉", aliases: ["かも肉"], romaji: ["kamoniku"] },

  { value: "ベーコン", romaji: ["bekon"] },
  { value: "ハム", romaji: ["hamu"] },
  { value: "生ハム", aliases: ["なまハム"], romaji: ["namahamu"] },
  { value: "ソーセージ", romaji: ["soseji"] },
  { value: "ウインナー", aliases: ["ウィンナー"], romaji: ["winna"] },
  { value: "サラミ", romaji: ["sarami"] },
  { value: "焼き豚", aliases: ["チャーシュー"], romaji: ["yakibuta", "chashu"] },
  { value: "コンビーフ", romaji: ["konbifu"] },

  { value: "鮭", aliases: ["さけ", "しゃけ", "サケ"], romaji: ["sake", "shake"] },
  { value: "塩鮭", aliases: ["しおざけ", "塩さけ"], romaji: ["shiozake"] },
  { value: "サーモン", romaji: ["samon"] },
  { value: "さば", aliases: ["鯖", "サバ"], romaji: ["saba"] },
  { value: "サバ缶", aliases: ["さば缶", "鯖缶"], romaji: ["sabakan"] },
  { value: "ぶり", aliases: ["鰤", "ブリ"], romaji: ["buri"] },
  { value: "たら", aliases: ["鱈", "タラ"], romaji: ["tara"] },
  { value: "あじ", aliases: ["鯵", "アジ"], romaji: ["aji"] },
  { value: "いわし", aliases: ["鰯", "イワシ"], romaji: ["iwashi"] },
  { value: "さんま", aliases: ["秋刀魚", "サンマ"], romaji: ["sanma"] },
  { value: "まぐろ", aliases: ["鮪", "マグロ"], romaji: ["maguro"] },
  { value: "かつお", aliases: ["鰹", "カツオ"], romaji: ["katsuo"] },
  { value: "たい", aliases: ["鯛", "タイ"], romaji: ["tai"] },
  { value: "ししゃも", romaji: ["shishamo"] },
  { value: "ほっけ", aliases: ["ホッケ"], romaji: ["hokke"] },
  { value: "さわら", aliases: ["鰆", "サワラ"], romaji: ["sawara"] },
  { value: "かれい", aliases: ["カレイ"], romaji: ["karei"] },
  { value: "めかじき", aliases: ["メカジキ"], romaji: ["mekajiki"] },
  { value: "しらす", romaji: ["shirasu"] },
  { value: "ちりめんじゃこ", aliases: ["じゃこ"], romaji: ["chirimenjako", "jako"] },
  { value: "明太子", aliases: ["めんたいこ"], romaji: ["mentaiko"] },
  { value: "たらこ", romaji: ["tarako"] },

  { value: "えび", aliases: ["海老", "エビ"], romaji: ["ebi"] },
  { value: "いか", aliases: ["烏賊", "イカ"], romaji: ["ika"] },
  { value: "たこ", aliases: ["蛸", "タコ"], romaji: ["tako"] },
  { value: "あさり", aliases: ["アサリ"], romaji: ["asari"] },
  { value: "しじみ", aliases: ["シジミ"], romaji: ["shijimi"] },
  { value: "ほたて", aliases: ["帆立", "ホタテ"], romaji: ["hotate"] },
  { value: "牡蠣", aliases: ["かき", "カキ"], romaji: ["kaki"] },
  { value: "カニカマ", aliases: ["かにかま"], romaji: ["kanikama"] },
  { value: "かに", aliases: ["蟹", "カニ"], romaji: ["kani"] },
  { value: "ちくわ", aliases: ["竹輪"], romaji: ["chikuwa"] },
  { value: "かまぼこ", aliases: ["蒲鉾"], romaji: ["kamaboko"] },
  { value: "はんぺん", romaji: ["hanpen"] },
  { value: "さつま揚げ", aliases: ["さつまあげ"], romaji: ["satsumaage"] },
  { value: "魚肉ソーセージ", aliases: ["ぎょにくソーセージ"], romaji: ["gyoniku"] },
  { value: "ツナ缶", aliases: ["ツナ", "まぐろ缶"], romaji: ["tsuna"] },

  { value: "キャベツ", romaji: ["kyabetsu"] },
  { value: "白菜", aliases: ["はくさい"], romaji: ["hakusai"] },
  { value: "レタス", romaji: ["retasu"] },
  { value: "サニーレタス", romaji: ["saniretasu"] },
  { value: "小松菜", aliases: ["こまつな"], romaji: ["komatsuna"] },
  { value: "ほうれん草", aliases: ["ほうれんそう"], romaji: ["horenso"] },
  { value: "チンゲン菜", aliases: ["青梗菜"], romaji: ["chingensai"] },
  { value: "しろ菜", aliases: ["しろな"], romaji: ["shirona"] },
  { value: "水菜", aliases: ["みずな"], romaji: ["mizuna"] },
  { value: "春菊", aliases: ["しゅんぎく"], romaji: ["shungiku"] },
  { value: "にら", aliases: ["ニラ"], romaji: ["nira"] },
  { value: "豆苗", aliases: ["とうみょう"], romaji: ["tomyo"] },
  { value: "大葉", aliases: ["おおば", "青じそ", "しそ"], romaji: ["oba", "shiso"] },
  { value: "パクチー", aliases: ["香菜", "コリアンダー"], romaji: ["pakuchi"] },
  { value: "三つ葉", aliases: ["みつば"], romaji: ["mitsuba"] },
  { value: "セロリ", romaji: ["serori"] },

  { value: "にんじん", aliases: ["人参", "ニンジン"], romaji: ["ninjin"] },
  { value: "じゃがいも", aliases: ["ジャガイモ"], romaji: ["jagaimo"] },
  { value: "さつまいも", aliases: ["サツマイモ"], romaji: ["satsumaimo"] },
  { value: "里芋", aliases: ["さといも"], romaji: ["satoimo"] },
  { value: "長芋", aliases: ["ながいも"], romaji: ["nagaimo"] },
  { value: "山芋", aliases: ["やまいも"], romaji: ["yamaimo"] },
  { value: "大根", aliases: ["だいこん"], romaji: ["daikon"] },
  { value: "かぶ", aliases: ["蕪"], romaji: ["kabu"] },
  { value: "れんこん", aliases: ["蓮根"], romaji: ["renkon"] },
  { value: "ごぼう", aliases: ["牛蒡"], romaji: ["gobo"] },
  { value: "たけのこ", aliases: ["筍"], romaji: ["takenoko"] },

  { value: "玉ねぎ", aliases: ["たまねぎ", "玉葱", "タマネギ"], romaji: ["tamanegi"] },
  { value: "新玉ねぎ", aliases: ["新たまねぎ"], romaji: ["shintamanegi"] },
  { value: "長ねぎ", aliases: ["長ネギ", "白ねぎ"], romaji: ["naganegi"] },
  { value: "青ねぎ", aliases: ["青ネギ", "小ねぎ"], romaji: ["aonegi"] },
  { value: "もやし", romaji: ["moyashi"] },
  { value: "きゅうり", aliases: ["胡瓜", "キュウリ"], romaji: ["kyuri"] },
  { value: "トマト", romaji: ["tomato"] },
  { value: "ミニトマト", romaji: ["minitomato"] },
  { value: "なす", aliases: ["茄子", "ナス"], romaji: ["nasu"] },
  { value: "ピーマン", romaji: ["piman"] },
  { value: "パプリカ", romaji: ["papurika"] },
  { value: "ズッキーニ", romaji: ["zucchini"] },
  { value: "かぼちゃ", aliases: ["南瓜", "カボチャ"], romaji: ["kabocha"] },
  { value: "とうもろこし", aliases: ["コーン"], romaji: ["tomorokoshi", "corn"] },
  { value: "オクラ", romaji: ["okura"] },
  { value: "ゴーヤ", aliases: ["にがうり", "苦瓜"], romaji: ["goya"] },
  { value: "アボカド", romaji: ["avocado"] },
  { value: "ブロッコリー", romaji: ["broccoli"] },
  { value: "カリフラワー", romaji: ["cauliflower"] },
  { value: "アスパラガス", aliases: ["アスパラ"], romaji: ["asupara"] },
  { value: "いんげん", aliases: ["インゲン"], romaji: ["ingen"] },
  { value: "絹さや", aliases: ["きぬさや"], romaji: ["kinusaya"] },
  { value: "スナップえんどう", aliases: ["スナップエンドウ"], romaji: ["sunappuendo"] },

  { value: "きのこ", romaji: ["kinoko"] },
  { value: "しめじ", romaji: ["shimeji"] },
  { value: "えのき", aliases: ["えのきだけ"], romaji: ["enoki"] },
  { value: "まいたけ", aliases: ["舞茸"], romaji: ["maitake"] },
  { value: "しいたけ", aliases: ["椎茸"], romaji: ["shiitake"] },
  { value: "エリンギ", romaji: ["eringi"] },
  { value: "マッシュルーム", romaji: ["mushroom"] },
  { value: "なめこ", romaji: ["nameko"] },

  { value: "わかめ", aliases: ["ワカメ"], romaji: ["wakame"] },
  { value: "ひじき", romaji: ["hijiki"] },
  { value: "のり", aliases: ["海苔"], romaji: ["nori"] },
  { value: "昆布", aliases: ["こんぶ"], romaji: ["konbu"] },
  { value: "塩昆布", aliases: ["しおこんぶ"], romaji: ["shiokonbu"] },
  { value: "切り干し大根", aliases: ["切干大根"], romaji: ["kiriboshidaikon"] },
  { value: "干ししいたけ", aliases: ["干し椎茸"], romaji: ["hoshishiitake"] },
  { value: "麩", aliases: ["ふ"], romaji: ["fu"] },
  { value: "こんにゃく", romaji: ["konnyaku"] },
  { value: "しらたき", romaji: ["shirataki"] },
  { value: "糸こんにゃく", romaji: ["itokonnyaku"] },

  { value: "キムチ", romaji: ["kimchi"] },
  { value: "梅干し", aliases: ["うめぼし"], romaji: ["umeboshi"] },
  { value: "たくあん", romaji: ["takuan"] },
  { value: "ザーサイ", romaji: ["zasai"] },
  { value: "紅しょうが", aliases: ["紅生姜"], romaji: ["benishoga"] },
  { value: "トマト缶", aliases: ["カットトマト缶", "ホールトマト缶"], romaji: ["tomatokan"] },
  { value: "コーン缶", romaji: ["cornkan"] },
  { value: "ミックスベジタブル", romaji: ["mixedvegetable"] },

  { value: "チーズ", romaji: ["cheese"] },
  { value: "ピザ用チーズ", aliases: ["とろけるチーズ"], romaji: ["pizayocheese"] },
  { value: "粉チーズ", aliases: ["パルメザンチーズ"], romaji: ["konacheese"] },
  { value: "クリームチーズ", romaji: ["creamcheese"] },
  { value: "牛乳", aliases: ["ぎゅうにゅう"], romaji: ["gyunyu"] },
  { value: "ヨーグルト", romaji: ["yogurt"] },
  { value: "生クリーム", aliases: ["なまクリーム"], romaji: ["namakurimu"] },
  { value: "バター", romaji: ["butter"] },

  { value: "りんご", aliases: ["林檎", "リンゴ"], romaji: ["ringo"] },
  { value: "バナナ", romaji: ["banana"] },
  { value: "みかん", aliases: ["蜜柑", "ミカン"], romaji: ["mikan"] },
  { value: "レモン", romaji: ["lemon"] },
  { value: "ゆず", aliases: ["柚子"], romaji: ["yuzu"] },
  { value: "いちご", aliases: ["苺", "イチゴ"], romaji: ["ichigo"] },
  { value: "ブルーベリー", romaji: ["blueberry"] },
  { value: "くるみ", aliases: ["胡桃"], romaji: ["kurumi"] },
  { value: "アーモンド", romaji: ["almond"] },
  { value: "ごま", aliases: ["胡麻", "ゴマ"], romaji: ["goma"] },
] as const satisfies readonly CandidateValue[];
