import type { CandidateValue } from "./types";

export const pairingTargetCandidates = [
  { value: "餃子", aliases: ["ぎょうざ", "ギョウザ"], romaji: ["gyoza"] },
  { value: "唐揚げ", aliases: ["から揚げ", "からあげ"], romaji: ["karaage"] },
  { value: "焼き魚", aliases: ["やきざかな"], romaji: ["yakizakana"] },
  { value: "肉じゃが", aliases: ["にくじゃが"], romaji: ["nikujaga"] },
  { value: "生姜焼き", aliases: ["しょうが焼き"], romaji: ["shogayaki"] },
  { value: "豚しゃぶ", romaji: ["butashabu"] },
  { value: "冷しゃぶ", aliases: ["ひやしゃぶ"], romaji: ["hiyashabu"] },
  { value: "照り焼きチキン", aliases: ["てりやきチキン"], romaji: ["teriyakichicken"] },
  { value: "チキンソテー", romaji: ["chickensote"] },
  { value: "ポークソテー", romaji: ["porksote"] },
  { value: "ステーキ", romaji: ["steak"] },
  { value: "焼肉", aliases: ["焼き肉"], romaji: ["yakiniku"] },
  { value: "とんかつ", aliases: ["トンカツ"], romaji: ["tonkatsu"] },
  { value: "チキン南蛮", aliases: ["チキンなんばん"], romaji: ["chickennanban"] },
  { value: "煮魚", aliases: ["にざかな"], romaji: ["nizakana"] },
  { value: "麻婆豆腐", aliases: ["マーボー豆腐"], romaji: ["mabodofu"] },
  { value: "八宝菜", aliases: ["はっぽうさい"], romaji: ["happosai"] },
  { value: "回鍋肉", aliases: ["ホイコーロー"], romaji: ["hoikoro"] },
  { value: "青椒肉絲", aliases: ["チンジャオロース"], romaji: ["chinjaorosu"] },
  { value: "エビチリ", aliases: ["えびチリ"], romaji: ["ebichiri"] },
  { value: "酢豚", aliases: ["すぶた"], romaji: ["subuta"] },
  { value: "春巻き", aliases: ["はるまき"], romaji: ["harumaki"] },
  { value: "焼売", aliases: ["しゅうまい", "シュウマイ"], romaji: ["shumai"] },
  { value: "野菜炒め", aliases: ["やさい炒め"], romaji: ["yasaiitame"] },
  { value: "肉野菜炒め", aliases: ["にくやさい炒め"], romaji: ["nikuyasaiitame"] },
  { value: "ゴーヤチャンプルー", aliases: ["ゴーヤチャンプル"], romaji: ["goyachanpuru"] },

  { value: "チャーハン", aliases: ["炒飯"], romaji: ["chahan"] },
  { value: "親子丼", aliases: ["おやこどん"], romaji: ["oyakodon"] },
  { value: "牛丼", aliases: ["ぎゅうどん"], romaji: ["gyudon"] },
  { value: "豚丼", aliases: ["ぶたどん"], romaji: ["butadon"] },
  { value: "かつ丼", aliases: ["カツ丼"], romaji: ["katsudon"] },
  { value: "天丼", aliases: ["てんどん"], romaji: ["tendon"] },
  { value: "そぼろ丼", romaji: ["soborodon"] },
  { value: "ちらし寿司", aliases: ["ちらしずし"], romaji: ["chirashizushi"] },
  { value: "寿司", aliases: ["すし", "鮨"], romaji: ["sushi"] },
  { value: "刺身", aliases: ["さしみ"], romaji: ["sashimi"] },
  { value: "炊き込みご飯", aliases: ["炊き込みごはん"], romaji: ["takikomigohan"] },
  { value: "混ぜご飯", aliases: ["混ぜごはん"], romaji: ["mazegohan"] },
  { value: "おにぎり", aliases: ["おむすび"], romaji: ["onigiri"] },
  { value: "焼きおにぎり", romaji: ["yakionigiri"] },
  { value: "ハヤシライス", romaji: ["hayashirice"] },

  { value: "そうめん", aliases: ["素麺"], romaji: ["somen"] },

  { value: "ラーメン", romaji: ["ramen"] },
  { value: "醤油ラーメン", aliases: ["しょうゆラーメン"], romaji: ["shoyu ramen"] },
  { value: "味噌ラーメン", aliases: ["みそラーメン"], romaji: ["miso ramen"] },
  { value: "塩ラーメン", aliases: ["しおラーメン"], romaji: ["shio ramen"] },
  { value: "豚骨ラーメン", aliases: ["とんこつラーメン"], romaji: ["tonkotsu ramen"] },
  { value: "担々麺", aliases: ["タンタンメン", "坦々麺"], romaji: ["tantanmen"] },
  { value: "冷やし中華", aliases: ["ひやし中華"], romaji: ["hiyashi chuka"] },
  { value: "つけ麺", aliases: ["つけめん"], romaji: ["tsukemen"] },

  { value: "パスタ", romaji: ["pasta"] },
  { value: "ミートソースパスタ", aliases: ["ミートソース"], romaji: ["meat sauce pasta"] },
  { value: "ナポリタン", romaji: ["naporitan"] },
  { value: "カルボナーラ", romaji: ["carbonara"] },
  { value: "ペペロンチーノ", romaji: ["peperoncino"] },
  { value: "トマトソースパスタ", aliases: ["トマトパスタ"], romaji: ["tomato sauce pasta"] },
  { value: "クリームパスタ", romaji: ["cream pasta"] },
  { value: "和風パスタ", romaji: ["wafu pasta"] },
  { value: "たらこパスタ", romaji: ["tarako pasta"] },
  { value: "明太子パスタ", aliases: ["めんたいこパスタ"], romaji: ["mentaiko pasta"] },
  { value: "ジェノベーゼ", romaji: ["genovese"] },
  { value: "ボンゴレ", romaji: ["vongole"] },

  { value: "鍋", aliases: ["なべ"], romaji: ["nabe"] },
  { value: "寄せ鍋", aliases: ["よせなべ"], romaji: ["yosenabe"] },
  { value: "キムチ鍋", aliases: ["キムチなべ"], romaji: ["kimchi nabe"] },
  { value: "豆乳鍋", aliases: ["とうにゅう鍋"], romaji: ["tonyu nabe"] },
  { value: "ちゃんこ鍋", aliases: ["ちゃんこ"], romaji: ["chanko nabe"] },
  { value: "水炊き", aliases: ["みずたき"], romaji: ["mizutaki"] },
  { value: "もつ鍋", aliases: ["もつなべ"], romaji: ["motsu nabe"] },
  { value: "しゃぶしゃぶ", romaji: ["shabu shabu"] },
  { value: "すき焼き", aliases: ["すきやき"], romaji: ["sukiyaki"] },
  { value: "湯豆腐", aliases: ["ゆどうふ"], romaji: ["yudofu"] },
  { value: "おでん", romaji: ["oden"] },

  { value: "うどん", romaji: ["udon"] },
  { value: "きつねうどん", romaji: ["kitsune udon"] },
  { value: "肉うどん", romaji: ["niku udon"] },
  { value: "カレーうどん", romaji: ["curry udon"] },
  { value: "釜玉うどん", aliases: ["かまたまうどん"], romaji: ["kamatama udon"] },
  { value: "焼きうどん", aliases: ["やきうどん"], romaji: ["yaki udon"] },
  { value: "冷やしうどん", aliases: ["ひやしうどん"], romaji: ["hiyashi udon"] },
  { value: "ぶっかけうどん", romaji: ["bukkake udon"] },

  { value: "そば", aliases: ["蕎麦"], romaji: ["soba"] },
  { value: "ざるそば", romaji: ["zaru soba"] },
  { value: "かけそば", romaji: ["kake soba"] },
  { value: "天ぷらそば", aliases: ["天そば"], romaji: ["tempura soba"] },
  { value: "月見そば", aliases: ["つきみそば"], romaji: ["tsukimi soba"] },
  { value: "とろろそば", romaji: ["tororo soba"] },
  { value: "鴨南蛮そば", aliases: ["鴨南蛮"], romaji: ["kamonanban soba"] },
  { value: "冷やしそば", aliases: ["ひやしそば"], romaji: ["hiyashi soba"] },

  { value: "カレー", romaji: ["curry"] },
  { value: "ビーフカレー", romaji: ["beef curry"] },
  { value: "ポークカレー", romaji: ["pork curry"] },
  { value: "チキンカレー", romaji: ["chicken curry"] },
  { value: "野菜カレー", aliases: ["やさいカレー"], romaji: ["vegetable curry"] },
  { value: "キーマカレー", romaji: ["keema curry"] },
  { value: "ドライカレー", romaji: ["dry curry"] },
  { value: "カツカレー", romaji: ["katsu curry"] },
  { value: "シーフードカレー", romaji: ["seafood curry"] },
  { value: "スープカレー", romaji: ["soup curry"] },
  { value: "カレーライス", romaji: ["curry rice"] },

  { value: "ハンバーグ", romaji: ["hamburg"] },
  { value: "チーズハンバーグ", romaji: ["cheese hamburg"] },
  { value: "和風ハンバーグ", romaji: ["wafu hamburg"] },
  { value: "煮込みハンバーグ", aliases: ["にこみハンバーグ"], romaji: ["nikomi hamburg"] },
  { value: "豆腐ハンバーグ", aliases: ["とうふハンバーグ"], romaji: ["tofu hamburg"] },
  { value: "おろしハンバーグ", romaji: ["oroshi hamburg"] },
  { value: "照り焼きハンバーグ", aliases: ["てりやきハンバーグ"], romaji: ["teriyaki hamburg"] },

  { value: "オムライス", romaji: ["chicken rice omurice"] },
  { value: "デミグラスオムライス", aliases: ["デミオムライス"], romaji: ["demiglace omurice"] },
  { value: "和風オムライス", romaji: ["wafu omurice"] },
  { value: "カレーオムライス", romaji: ["curry omurice"] },

  { value: "ドリア", romaji: ["doria"] },
  { value: "チキンドリア", romaji: ["chicken doria"] },
  { value: "ミートドリア", romaji: ["meat doria"] },
  { value: "カレードリア", romaji: ["curry doria"] },
  { value: "シーフードドリア", romaji: ["seafood doria"] },
  { value: "きのこドリア", romaji: ["kinoko doria"] },

  { value: "ピザ", romaji: ["pizza"] },
  { value: "マルゲリータピザ", aliases: ["マルゲリータ"], romaji: ["margherita pizza"] },
  {
    value: "照り焼きチキンピザ",
    aliases: ["てりやきチキンピザ"],
    romaji: ["teriyaki chicken pizza"],
  },
  { value: "シーフードピザ", romaji: ["seafood pizza"] },
  { value: "チーズピザ", romaji: ["cheese pizza"] },
  { value: "ミックスピザ", romaji: ["mixed pizza"] },
  { value: "野菜ピザ", aliases: ["やさいピザ"], romaji: ["vegetable pizza"] },

  { value: "サンドイッチ", romaji: ["sandwich"] },
  { value: "卵サンド", aliases: ["たまごサンド", "玉子サンド"], romaji: ["egg sandwich"] },
  { value: "ハムサンド", romaji: ["ham sandwich"] },
  { value: "ツナサンド", romaji: ["tuna sandwich"] },
  { value: "カツサンド", romaji: ["katsu sandwich"] },
  { value: "BLTサンド", aliases: ["BLT"], romaji: ["blt sandwich"] },
  { value: "ホットサンド", romaji: ["hot sandwich"] },
  { value: "フルーツサンド", romaji: ["fruit sandwich"] },

  { value: "シチュー", romaji: ["stew"] },
  { value: "クリームシチュー", romaji: ["cream stew"] },
  { value: "ビーフシチュー", romaji: ["beef stew"] },
  { value: "ブラウンシチュー", romaji: ["brown stew"] },
  { value: "豆乳シチュー", aliases: ["とうにゅうシチュー"], romaji: ["tonyu stew"] },
  { value: "かぼちゃシチュー", romaji: ["kabocha stew"] },

  { value: "グラタン", romaji: ["gratin"] },
  { value: "マカロニグラタン", romaji: ["macaroni gratin"] },
  { value: "ポテトグラタン", romaji: ["potato gratin"] },
  { value: "チキングラタン", romaji: ["chicken gratin"] },
  { value: "シーフードグラタン", romaji: ["seafood gratin"] },
  { value: "なすグラタン", romaji: ["nasu gratin"] },
  { value: "かぼちゃグラタン", romaji: ["kabocha gratin"] },
  { value: "豆腐グラタン", aliases: ["とうふグラタン"], romaji: ["tofu gratin"] },

  { value: "焼きそば", aliases: ["やきそば"], romaji: ["yakisoba"] },
  { value: "ジャージャー麺", aliases: ["ジャージャーめん"], romaji: ["jajamen"] },
  { value: "お好み焼き", aliases: ["おこのみやき"], romaji: ["okonomiyaki"] },
  { value: "たこ焼き", aliases: ["たこやき"], romaji: ["takoyaki"] },

  { value: "味噌汁", aliases: ["みそ汁", "みそしる"], romaji: ["misoshiru"] },
  { value: "豚汁", aliases: ["とん汁", "ぶた汁"], romaji: ["tonjiru"] },
  { value: "けんちん汁", romaji: ["kenchinjiru"] },
  { value: "すまし汁", aliases: ["お吸い物"], romaji: ["sumashijiru"] },
  { value: "コーンスープ", romaji: ["cornsoup"] },
  { value: "ミネストローネ", romaji: ["minestrone"] },
  { value: "ポトフ", romaji: ["potofu"] },
  { value: "鍋", aliases: ["なべ"], romaji: ["nabe"] },

  { value: "卵焼き", aliases: ["玉子焼き", "たまご焼き"], romaji: ["tamagoyaki"] },
  { value: "だし巻き卵", aliases: ["だし巻き玉子"], romaji: ["dashimakitamago"] },
  { value: "冷奴", aliases: ["ひややっこ"], romaji: ["hiyayakko"] },
  { value: "納豆", aliases: ["なっとう"], romaji: ["natto"] },
  { value: "茶碗蒸し", aliases: ["ちゃわんむし"], romaji: ["chawanmushi"] },
  { value: "ポテトサラダ", romaji: ["potatosalad"] },
  { value: "マカロニサラダ", romaji: ["macaronisalad"] },
  { value: "春雨サラダ", aliases: ["はるさめサラダ"], romaji: ["harusamesalad"] },
  { value: "コールスロー", romaji: ["coleslaw"] },
] as const satisfies readonly CandidateValue[];
