import type { CandidateValue } from "./types";

export const recipeDirectionCandidates = [
  { value: "あっさり", romaji: ["assari"] },
  { value: "さっぱり", romaji: ["sappari"] },
  { value: "甘辛", aliases: ["あまから"], romaji: ["amakara"] },
  { value: "甘め", aliases: ["甘い"], romaji: ["amame"] },
  { value: "しょっぱめ", aliases: ["塩気強め"], romaji: ["shoppame"] },
  { value: "こってり", romaji: ["kotteri"] },
  { value: "濃いめ", aliases: ["濃い味"], romaji: ["koime"] },
  { value: "薄味", aliases: ["うす味"], romaji: ["usuaji"] },
  { value: "やさしい味", aliases: ["優しい味"], romaji: ["yasashii aji"] },
  { value: "ご飯が進む", aliases: ["ごはんが進む"], romaji: ["gohan ga susumu"] },
  { value: "だし系", aliases: ["だし味"], romaji: ["dashi"] },
  { value: "うま味重視", aliases: ["旨味重視"], romaji: ["umami"] },
  { value: "ピリ辛", aliases: ["ぴり辛"], romaji: ["pirikara"] },
  { value: "辛くない", aliases: ["辛さなし"], romaji: ["karakunai"] },
  { value: "酸味あり", aliases: ["酸っぱい"], romaji: ["sanmi"] },
  { value: "香ばしい", aliases: ["こうばしい"], romaji: ["kobashii"] },
  { value: "クリーミー", romaji: ["creamy"] },
  { value: "スパイシー", romaji: ["spicy"] },
  { value: "にんにく風味", aliases: ["ニンニク風味"], romaji: ["ninniku"] },
  { value: "しょうが風味", aliases: ["生姜風味"], romaji: ["shoga"] },
  { value: "ごま風味", aliases: ["胡麻風味"], romaji: ["goma"] },
  { value: "味噌味", aliases: ["みそ味"], romaji: ["miso"] },
  { value: "しょうゆ味", aliases: ["醤油味"], romaji: ["shoyu"] },
  { value: "塩味", aliases: ["しお味"], romaji: ["shio"] },
  { value: "ソース味", romaji: ["sauce"] },
  { value: "ケチャップ味", romaji: ["ketchup"] },

  { value: "和風", aliases: ["和食", "わふう"], romaji: ["wafu", "washoku"] },
  { value: "洋風", aliases: ["洋食", "ようふう"], romaji: ["yofu", "yoshoku"] },
  { value: "中華風", aliases: ["中華", "ちゅうかふう"], romaji: ["chuka"] },
  { value: "韓国風", aliases: ["韓国料理", "かんこくふう"], romaji: ["kankoku"] },
  { value: "イタリアン", aliases: ["イタリア風", "いたりあん"], romaji: ["italian"] },
  { value: "フレンチ風", aliases: ["フランス風", "ふれんちふう"], romaji: ["french"] },
  { value: "エスニック", romaji: ["ethnic"] },
  { value: "タイ風", aliases: ["タイ料理"], romaji: ["thai"] },
  { value: "ベトナム風", aliases: ["ベトナム料理"], romaji: ["vietnam"] },
  { value: "インド風", aliases: ["インド料理"], romaji: ["india"] },
  { value: "カレー風", aliases: ["かれーふう"], romaji: ["curry"] },
  { value: "沖縄風", aliases: ["沖縄料理", "おきなわふう"], romaji: ["okinawa"] },
  { value: "和洋折衷", romaji: ["wayo setchu"] },
  { value: "居酒屋風", romaji: ["izakaya"] },
  { value: "カフェ風", romaji: ["cafe"] },
  { value: "給食風", romaji: ["kyushoku"] },

  { value: "野菜たっぷり", aliases: ["野菜多め"], romaji: ["yasai tappuri"] },
  { value: "栄養バランス", aliases: ["栄養バランス重視"], romaji: ["eiyo balance"] },
  { value: "たんぱく質多め", aliases: ["タンパク質多め"], romaji: ["protein"] },
  { value: "食物繊維多め", romaji: ["shokumotsuseni"] },
  { value: "鉄分多め", romaji: ["tetsubun"] },
  { value: "カルシウム多め", romaji: ["calcium"] },
  { value: "塩分控えめ", aliases: ["減塩"], romaji: ["genen"] },
  { value: "脂質控えめ", romaji: ["shishitsu hikaeme"] },
  { value: "低カロリー", aliases: ["カロリー控えめ"], romaji: ["teikarori"] },
  { value: "低糖質", aliases: ["糖質控えめ"], romaji: ["teitoshitsu"] },
  { value: "消化にやさしい", aliases: ["消化が良い"], romaji: ["shoka ni yasashii"] },
  { value: "胃にやさしい", aliases: ["胃に優しい"], romaji: ["i ni yasashii"] },
  { value: "ダイエット向き", aliases: ["ダイエット"], romaji: ["diet"] },
  { value: "ヘルシー", romaji: ["healthy"] },
  { value: "発酵食品を使う", aliases: ["発酵食品"], romaji: ["hakko"] },
  { value: "温まる", aliases: ["体が温まる"], romaji: ["atatamaru"] },
  { value: "夏バテ対策", romaji: ["natsubate"] },

  { value: "平日夕食", aliases: ["平日の夕食"], romaji: ["heijitsu yushoku"] },
  { value: "朝食", aliases: ["朝ごはん"], romaji: ["choshoku"] },
  { value: "昼食", aliases: ["昼ごはん"], romaji: ["chushoku"] },
  { value: "夜食", romaji: ["yashoku"] },
  { value: "休日ごはん", aliases: ["休日"], romaji: ["kyujitsu"] },
  { value: "作り置き", aliases: ["つくりおき"], romaji: ["tsukurioki"] },
  { value: "お弁当", aliases: ["弁当"], romaji: ["bento"] },
  { value: "おつまみ", aliases: ["つまみ"], romaji: ["otsumami"] },
  { value: "子ども向け", aliases: ["子供向け"], romaji: ["kodomo"] },
  { value: "幼児向け", romaji: ["yoji"] },
  { value: "シニア向け", aliases: ["高齢者向け"], romaji: ["senior"] },
  { value: "来客", aliases: ["来客向け"], romaji: ["raikyaku"] },
  { value: "おもてなし", romaji: ["omotenashi"] },
  { value: "パーティー", romaji: ["party"] },
  { value: "一人ごはん", aliases: ["ひとりごはん"], romaji: ["hitorigohan"] },
  { value: "家族向け", romaji: ["kazoku"] },
  { value: "風邪気味", aliases: ["風邪の日"], romaji: ["kaze"] },
  { value: "食欲がない日", aliases: ["食欲なし"], romaji: ["shokuyoku"] },
  { value: "暑い日", romaji: ["atsuihi"] },
  { value: "寒い日", romaji: ["samuihi"] },

  { value: "カリカリ", romaji: ["karikari"] },
  { value: "サクサク", romaji: ["sakusaku"] },
  { value: "ふわふわ", romaji: ["fuwafuwa"] },
  { value: "とろとろ", romaji: ["torotoro"] },
  { value: "もちもち", romaji: ["mochimochi"] },
  { value: "シャキシャキ", romaji: ["shakishaki"] },
  { value: "しっとり", romaji: ["shittori"] },
  { value: "ジューシー", romaji: ["juicy"] },
  { value: "やわらかめ", aliases: ["柔らかめ"], romaji: ["yawarakame"] },
  { value: "噛みごたえあり", aliases: ["噛み応えあり"], romaji: ["kamigotae"] },
] as const satisfies readonly CandidateValue[];
