import type { CandidateValue } from "./types";

export const seasoningCandidates = [
  { value: "塩", aliases: ["しお"], romaji: ["shio"] },
  { value: "こしょう", aliases: ["胡椒", "コショウ"], romaji: ["kosho"] },
  { value: "砂糖", aliases: ["さとう"], romaji: ["sato"] },
  { value: "しょうゆ", aliases: ["醤油", "しょう油"], romaji: ["shoyu"] },
  { value: "味噌", aliases: ["みそ", "ミソ"], romaji: ["miso"] },
  { value: "酢", aliases: ["お酢", "す"], romaji: ["su"] },
  { value: "米酢", aliases: ["こめ酢"], romaji: ["komezu"] },
  { value: "みりん", aliases: ["味醂"], romaji: ["mirin"] },
  { value: "酒", aliases: ["料理酒"], romaji: ["sake", "ryorishu"] },
  { value: "めんつゆ", aliases: ["麺つゆ"], romaji: ["mentsuyu"] },
  { value: "白だし", aliases: ["しろだし"], romaji: ["shirodashi"] },
  { value: "だしの素", aliases: ["顆粒だし"], romaji: ["dashinomoto"] },
  { value: "コンソメ", romaji: ["consomme"] },
  { value: "鶏ガラスープの素", aliases: ["鶏がらスープの素"], romaji: ["torigarasupu"] },
  { value: "マヨネーズ", aliases: ["マヨ"], romaji: ["mayonnaise", "mayo"] },
  { value: "ケチャップ", romaji: ["ketchup"] },
  { value: "ソース", romaji: ["sauce"] },
  { value: "ウスターソース", romaji: ["worcester"] },
  { value: "中濃ソース", aliases: ["ちゅうのうソース"], romaji: ["chunosauce"] },
  { value: "オイスターソース", romaji: ["oystersauce"] },
  { value: "ごま油", aliases: ["胡麻油"], romaji: ["gomaabura"] },
  { value: "サラダ油", romaji: ["saradaabura"] },
  { value: "オリーブオイル", romaji: ["oliveoil"] },
  { value: "バター", romaji: ["butter"] },
  { value: "ラー油", aliases: ["辣油"], romaji: ["rayu"] },
  { value: "豆板醤", aliases: ["とうばんじゃん"], romaji: ["tobanjan"] },
  { value: "コチュジャン", romaji: ["gochujang"] },
  { value: "甜麺醤", aliases: ["てんめんじゃん"], romaji: ["tenmenjan"] },
  { value: "味覇", aliases: ["ウェイパー"], romaji: ["weipa"] },
  { value: "カレー粉", aliases: ["カレーパウダー"], romaji: ["kareko"] },
  { value: "唐辛子", aliases: ["とうがらし", "鷹の爪"], romaji: ["togarashi"] },
  { value: "にんにく", aliases: ["ニンニク", "大蒜"], romaji: ["ninniku"] },
  { value: "しょうが", aliases: ["生姜", "ショウガ"], romaji: ["shoga"] },
  { value: "わさび", aliases: ["山葵"], romaji: ["wasabi"] },
  { value: "からし", aliases: ["辛子"], romaji: ["karashi"] },
  { value: "山椒", aliases: ["さんしょう"], romaji: ["sansho"] },
  { value: "七味唐辛子", aliases: ["七味"], romaji: ["shichimi"] },
  { value: "一味唐辛子", aliases: ["一味"], romaji: ["ichimi"] },
  { value: "ハーブソルト", romaji: ["herbsalt"] },
  { value: "ブラックペッパー", aliases: ["黒こしょう"], romaji: ["blackpepper"] },
  { value: "粉チーズ", aliases: ["パルメザンチーズ"], romaji: ["konacheese"] },
  { value: "レモン汁", aliases: ["レモン果汁"], romaji: ["lemonjiru"] },
  { value: "ポン酢", aliases: ["ぽん酢"], romaji: ["ponzu"] },
  { value: "焼肉のたれ", aliases: ["焼き肉のたれ"], romaji: ["yakinikunotare"] },
  { value: "ドレッシング", romaji: ["dressing"] },
] as const satisfies readonly CandidateValue[];
