import type { ComboConfig, OptionSetKey, ServingGroup } from "./types";

export const cookTimeOptions = [
  "",
  "3分以内",
  "5分以内",
  "10分以内",
  "15分以内",
  "20分以内",
  "30分以内",
  "45分以内",
  "60分以内",
] as const;

export const servingGroups = [
  { id: "adultCount", label: "大人", icon: "adult" },
  { id: "seniorCount", label: "シニア(60歳以上)", icon: "senior" },
  { id: "childCount", label: "子供(12歳以下)", icon: "child" },
  { id: "toddlerCount", label: "幼児(5歳以下)", icon: "baby" },
] as const satisfies readonly ServingGroup[];

export const optionSets: Record<OptionSetKey, string[]> = {
  materials: [
    "米",
    "ご飯",
    "もち",
    "食パン",
    "うどん",
    "そば",
    "そうめん",
    "パスタ",
    "中華麺",
    "春雨",
    "オートミール",
    "卵",
    "豆腐",
    "厚揚げ",
    "油揚げ",
    "納豆",
    "おから",
    "高野豆腐",
    "豆乳",
    "鶏もも肉",
    "鶏むね肉",
    "鶏ささみ",
    "鶏ひき肉",
    "豚こま肉",
    "豚バラ肉",
    "豚ひき肉",
    "豚ロース",
    "牛こま肉",
    "牛ひき肉",
    "合いびき肉",
    "ベーコン",
    "ハム",
    "ソーセージ",
    "ツナ缶",
    "サバ缶",
    "鮭",
    "塩鮭",
    "さば",
    "ぶり",
    "たら",
    "あじ",
    "ししゃも",
    "ちくわ",
    "かまぼこ",
    "カニカマ",
    "えび",
    "いか",
    "あさり",
    "玉ねぎ",
    "長ねぎ",
    "青ねぎ",
    "にんじん",
    "じゃがいも",
    "さつまいも",
    "里芋",
    "大根",
    "かぶ",
    "れんこん",
    "ごぼう",
    "キャベツ",
    "白菜",
    "レタス",
    "小松菜",
    "ほうれん草",
    "チンゲン菜",
    "しろ菜",
    "水菜",
    "春菊",
    "にら",
    "もやし",
    "きゅうり",
    "トマト",
    "ミニトマト",
    "なす",
    "ピーマン",
    "パプリカ",
    "ズッキーニ",
    "かぼちゃ",
    "ブロッコリー",
    "カリフラワー",
    "アスパラガス",
    "オクラ",
    "とうもろこし",
    "枝豆",
    "いんげん",
    "絹さや",
    "スナップえんどう",
    "アボカド",
    "きのこ",
    "しめじ",
    "えのき",
    "まいたけ",
    "しいたけ",
    "エリンギ",
    "マッシュルーム",
    "わかめ",
    "ひじき",
    "のり",
    "昆布",
    "切り干し大根",
    "こんにゃく",
    "しらたき",
    "キムチ",
    "梅干し",
    "チーズ",
    "牛乳",
    "ヨーグルト",
    "バター",
  ],
  dishTypes: [
    "主菜",
    "副菜",
    "汁物",
    "ご飯もの",
    "サラダ",
    "作り置き",
    "お弁当おかず",
    "麺類",
    "おつまみ",
  ],
  cookingTools: [
    "電子レンジ",
    "フライパン",
    "鍋",
    "ホットクック",
    "炊飯器",
    "トースター",
    "オーブン",
    "魚焼きグリル",
    "火を使わない",
    "和えるだけ",
    "蒸す",
    "揚げない",
  ],
  pairingTargets: [
    "カレー",
    "餃子",
    "唐揚げ",
    "ハンバーグ",
    "焼き魚",
    "肉じゃが",
    "生姜焼き",
    "味噌汁",
    "鍋",
    "オムライス",
    "チャーハン",
    "うどん",
    "そば",
    "ラーメン",
    "焼きそば",
    "パスタ",
    "親子丼",
    "牛丼",
    "豚丼",
    "かつ丼",
    "おでん",
    "シチュー",
    "麻婆豆腐",
    "焼肉",
    "とんかつ",
    "刺身",
    "寿司",
    "炊き込みご飯",
    "おにぎり",
    "サンドイッチ",
    "卵焼き",
    "冷奴",
    "納豆",
    "豚汁",
    "チキン南蛮",
    "煮魚",
    "グラタン",
    "ドリア",
    "ナポリタン",
    "そうめん",
    "焼き餃子",
    "水餃子",
    "ハヤシライス",
    "ステーキ",
    "すき焼き",
    "しゃぶしゃぶ",
    "寄せ鍋",
    "キムチ鍋",
    "ちらし寿司",
    "天丼",
    "そぼろ丼",
    "混ぜご飯",
    "ピザ",
    "けんちん汁",
    "すまし汁",
    "コーンスープ",
    "ポトフ",
    "八宝菜",
    "回鍋肉",
    "青椒肉絲",
    "エビチリ",
    "酢豚",
    "春巻き",
    "焼売",
    "茶碗蒸し",
  ],
  difficulty: [
    "時短",
    "洗い物少なめ",
    "手順少なめ",
    "節約",
    "初心者向け",
    "失敗しにくい",
    "包丁少なめ",
    "ボリューム重視",
  ],
  health: [
    "野菜多め",
    "たんぱく質多め",
    "塩分控えめ",
    "低カロリー",
    "脂質控えめ",
    "食物繊維多め",
    "低糖質",
    "消化にやさしい",
  ],
  flavors: [
    "あっさり",
    "さっぱり",
    "甘辛",
    "ご飯が進む",
    "やさしい味",
    "こってり",
    "だし系",
    "ピリ辛",
    "酸味あり",
  ],
  genres: ["和食", "中華", "洋食", "韓国風", "イタリアン", "カレー風", "和洋折衷", "エスニック"],
  scenes: [
    "平日夕食",
    "作り置き",
    "お弁当",
    "子ども向け",
    "朝食",
    "昼食",
    "おつまみ",
    "夜食",
    "来客",
  ],
  ngSeasonings: [
    "にんにく",
    "唐辛子",
    "砂糖",
    "塩",
    "しょうゆ",
    "味噌",
    "ごま油",
    "マヨネーズ",
    "こしょう",
    "しょうが",
    "酢",
    "みりん",
    "酒",
    "豆板醤",
    "オリーブオイル",
    "ケチャップ",
    "ソース",
  ],
};

export const combos: ComboConfig[] = [
  {
    id: "materials",
    label: "材料",
    icon: "leaf",
    optionSet: "materials",
    placeholder: "例: 卵、豆腐、もやし",
    prompt: "材料",
    bullets: true,
    basic: true,
  },
  {
    id: "dishTypes",
    label: "作りたいもの",
    icon: "bowl",
    optionSet: "dishTypes",
    placeholder: "例: 副菜",
    prompt: "作りたいもの",
    basic: true,
  },
  {
    id: "cookingTools",
    label: "調理方法・器具",
    icon: "pot",
    optionSet: "cookingTools",
    placeholder: "例: 電子レンジ",
    prompt: "調理方法・器具",
    basic: true,
  },
  {
    id: "pairingTargets",
    label: "一緒に出す料理、合わせたい料理",
    icon: "link",
    optionSet: "pairingTargets",
    placeholder: "例: カレー",
    prompt: "一緒に出す料理、合わせたい料理",
    basic: true,
    chip: "一緒に出す",
  },
  {
    id: "difficulty",
    label: "作りやすさ",
    icon: "zap",
    optionSet: "difficulty",
    placeholder: "例: 時短",
    prompt: "作りやすさ",
  },
  {
    id: "health",
    label: "栄養・健康",
    icon: "heart",
    optionSet: "health",
    placeholder: "例: 野菜多め",
    prompt: "栄養・健康",
  },
  {
    id: "flavors",
    label: "味つけ",
    icon: "salt",
    optionSet: "flavors",
    placeholder: "例: あっさり",
    prompt: "味つけ",
  },
  {
    id: "genres",
    label: "ジャンル",
    icon: "globe",
    optionSet: "genres",
    placeholder: "例: 和食",
    prompt: "ジャンル",
  },
  {
    id: "scenes",
    label: "シーン",
    icon: "bag",
    optionSet: "scenes",
    placeholder: "例: 平日夕食",
    prompt: "シーン",
  },
  {
    id: "ngMaterials",
    label: "NG材料",
    icon: "ban",
    optionSet: "materials",
    placeholder: "例: にんじん",
    prompt: "NG材料",
  },
  {
    id: "ngSeasonings",
    label: "NG調味料",
    icon: "alert",
    optionSet: "ngSeasonings",
    placeholder: "例: にんにく",
    prompt: "NG調味料",
  },
];

export const advancedComboOrder = [
  "difficulty",
  "health",
  "flavors",
  "genres",
  "scenes",
  "ngMaterials",
  "ngSeasonings",
] as const;

export const chipOrder = [
  "materials",
  "dishTypes",
  "cookingTools",
  "pairingTargets",
  "difficulty",
  "health",
  "flavors",
  "genres",
  "scenes",
  "ngMaterials",
  "ngSeasonings",
] as const;
